/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./pottedPlant.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.potted_plant_02_pot.geometry}
        material={materials.potted_plant_02_pot}
      />
      <mesh
        geometry={nodes.potted_plant_02_leaves.geometry}
        material={materials.potted_plant_02_leaves}
        position={[0, 0.31, 0]}
      />
      <mesh
        geometry={nodes.potted_plant_02_dirt.geometry}
        material={materials.potted_plant_02_pot}
        position={[-0.13, 0.32, -0.13]}
      />
    </group>
  );
}

useGLTF.preload("/pottedPlant.gltf");
