/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, SpotLight, Sparkles } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/lampada.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 3.37, 0]} scale={[0.1, 0.32, 0.1]}>
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.002"]}
        />
        <pointLight color="lightyellow" power={1} />
        <mesh
          geometry={nodes.Cylinder_1.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/lampada.glb");
